version: "3.1"
services:
  namingserver:
    image: midarch/fibonaccidistributed:1.14.0-namingserver-tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "1"
          memory: 128M
        reservations:
          cpus: "1"
          memory: 128M

  server:
    image: midarch/fibonaccidistributed:1.14.0-server-tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "1"
          memory: 128M
        reservations:
          cpus: "1"
          memory: 128M

  client:
    image: midarch/fibonaccidistributed:1.14.0-client-tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "1"
          memory: 128M
        reservations:
          cpus: "1"
          memory: 128M
    environment:
      FIBONACCI_PLACE: "38"
      SAMPLE_SIZE: "10000"
      AVERAGE_WAITING_TIME: "200"
